---
- name: Download WordPress
  get_url:
    url=https://wordpress.org/latest.tar.gz
    dest=/tmp/wordpress.tar.gz
    validate_certs=no

- name: Extract wordpress
  unarchive:
    src: /tmp/wordpress.tar.gz
    dest: /var/www/html
    remote_src: yes
    extra_opts: "--strip-components=1"

- name: Fetch random salts for WordPress config
  local_action: command curl https://api.wordpress.org/secret-key/1.1/salt/
  register: "wp_salt"

#- name: Copy sample config file
#  command: cp /var/www/html/wp-config-sample.php /var/www/html/wp-config.php creates=/var/www/html/wp-config.php

- name: Copy WordPress config file
  template: src=wp-config.php.j2 dest=/var/www/html/wp-config.php

- name: Update ownership to Apache user
  file:
    path: /var/www/html/
    state: directory
    recurse: yes
    owner: www-data
    group: www-data

- name: Set the permissions
  command: find /var/www/html/ -type d -exec chmod 750 {} \;

- name: Set the correct permissions for Wordpress files
  command: find /var/www/html/ -type f -exec chmod 640 {} \;
  notify:
    - restart apache
